name: Stok Takibi

on:
  schedule:
    - cron: '0 * * * *'     # Her saat başı çalışır
  workflow_dispatch:         # Elle de başlatabilirsin

jobs:
  run-stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python'ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gereken kütüphaneleri yükle
        run: |
          pip install -r requirements.txt

      - name: Ortam değişkenlerini ayarla ve scripti çalıştır
        env:
          GITHUB_ACTIONS: "true"
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python stockChecker.py
