name: Stok Takibi

on:
  schedule:
    - cron: '0 * * * *'     # Her saat başı çalışır
  workflow_dispatch:

permissions:
  contents: write  # push izni için şart

jobs:
  run-stock-check:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      GITHUB_ACTIONS: true

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python'ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Stok kontrolü çalıştır
        run: python stockChecker.py

      - name: Değişiklikleri commit et ve pushla
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add urun.json
          git commit -m "Stok durumu otomatik güncelleme [skip ci]" || echo "Değişiklik yok"
          git push origin main
