name: Stok Kontrol

on:
  schedule:
    - cron: '*/10 * * * *'   # Her 10 dakikada bir çalıştır
  workflow_dispatch:          # İstersen manuel de tetikleyebilirsin

jobs:
  stok-kontrol:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Stok kontrol scriptini çalıştır
        run: python check_stock.py

      - name: Güncellenen JSON dosyasını commit et
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add urunler.json
          git commit -m "Güncellenen stok durumu"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
