name: Stock Checker

on:
  schedule:
    - cron: '*/10 * * * *'  # Her 10 dakikada bir çalışır
  workflow_dispatch:  # Manuel çalıştırma desteği

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Gereksinimleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ortam değişkenlerini ayarla
      run: |
        echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> $GITHUB_ENV
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
        echo "EMAIL_RECEIVER=${{ secrets.EMAIL_RECEIVER }}" >> $GITHUB_ENV

    - name: Stok kontrolü scriptini çalıştır
      run: python python path/to/stock_check.py
