name: Stok Takibi

on:
  schedule:
    - cron: '0 * * * *'     # Her saat başı çalışır
  workflow_dispatch:         # Elle de başlatabilirsin

jobs:
  run-stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Sonraki push işlemi için gerekli

      - name: Python'ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install flask selenium webdriver-manager pandas openpyxl apscheduler

      - name: Chrome ve ChromeDriver kur
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Stok kontrolünü çalıştır
        env:
          GITHUB_ACTIONS: "true"
        run: |
          python stockChecker.py

      - name: Değişiklikleri kaydet ve pushla
        if: always()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add urun.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Stok durumu otomatik güncelleme [skip ci]" && git push)