name: Stok Takibi

on:
  schedule:
    - cron: '0 * * * *'     # Her saat başı çalışır
  workflow_dispatch:         # Elle de başlatabilirsin

jobs:
  run-stock-check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python'ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Google Chrome ve ChromeDriver kur
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          wget -N https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Gereken kütüphaneleri yükle
        run: |
          pip install -r requirements.txt || true  # varsa yükler, yoksa geçer
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager flask pandas

      - name: Ortam değişkenlerini ayarla ve scripti çalıştır
        env:
          GITHUB_ACTIONS: "true"
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python stockChecker.py
